### PR TITLE
Spring Boot 3.x

### PR DESCRIPTION
**Pull request by timtebeek**
Via: https://docs.openrewrite.org/recipes/java/spring/boot3/upgradespringboot_3_0
```
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-spring:RELEASE \
  -Drewrite.activeRecipes=org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_0
```

### CODE REVIEW

**Comment by doychin** [comment]
We are still using Java 11. Text blocks will not work.

**Comment by timtebeek** [comment]
> We are still using Java 11. Text blocks will not work.

In that case you're better off first looking at https://github.com/bgjug/jprime/pull/238, as Spring Boot 3 requires Java 17.

Here are instructions if you would want to first, and separately, like to upgrade to Java 17:
https://docs.openrewrite.org/running-recipes/popular-recipe-guides/migrate-to-java-17
https://docs.openrewrite.org/recipes/java/migrate/upgradetojava17
```
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:RELEASE \
  -Drewrite.activeRecipes=org.openrewrite.java.migrate.UpgradeToJava17
```

**Comment by timtebeek** [comment]
With OSS support for Spring Boot 2.7 expiring a month from now, it might be good to reconsider a move to Spring Boot 3.1 & Java 17.

**Comment by timtebeek** [comment]
Seeing the conflicts in this PR I think it's best to close this one; it was created in a mostly automated fashion; here's a quick guide if you're looking to migrate still.

## Leap to Spring Boot 3.1

You will want to [run the Migrate Spring Boot 3.1 recipe](https://docs.openrewrite.org/recipes/java/spring/boot3/upgradespringboot_3_1), which runs you through all the steps of migrating to Spring Boot 3.1, no matter what version you're coming from.

## Migrate in steps

If you'd rather migrate in steps, you can also run recipes individually. This can be helpful if you'd like to review and
build confidence in the changes, or need to troubleshoot a particular aspect.

As you can see in [the Migrate Spring Boot 3.1 recipe](https://docs.openrewrite.org/recipes/java/spring/boot3/upgradespringboot_3_1), that first takes you [to Spring Boot 3.0](https://docs.openrewrite.org/recipes/java/spring/boot3/upgradespringboot_3_0), which first takes
you [to Spring Boot 2.7](https://docs.openrewrite.org/recipes/java/spring/boot2/upgradespringboot_2_7), which first takes you [to Spring Boot 2.6](https://docs.openrewrite.org/recipes/java/spring/boot2/upgradespringboot_2_6), ... You can run any of these intermediate recipes, to pick up the changes up to that point.

You can also pick out specific migrations, for as much as you aren't up-to-date already, such as

- [Migrate Spring Boot 2.x projects to JUnit 5 from JUnit 4](https://docs.openrewrite.org/recipes/java/spring/boot2/springboot2junit4to5migration)
- [Migrate to Java 17](https://docs.openrewrite.org/recipes/java/migrate/upgradetojava17), which of course
  includes [Migrate to Java 11](https://docs.openrewrite.org/recipes/java/migrate/java8tojava11)
- [Migrate to Spring Security 5.8](https://docs.openrewrite.org/recipes/java/spring/security5/upgradespringsecurity_5_8)
- [Spring Boot 2.x best practices](https://docs.openrewrite.org/recipes/java/spring/boot2/springboot2bestpractices)

## Best practices after you migrate

After you've migrated to Spring Boot 3.1, you might want to consider some of the following best practices:

- [Common static analysis issues](https://docs.openrewrite.org/recipes/staticanalysis/commonstaticanalysis)
- [JUnit Jupiter best practices](https://docs.openrewrite.org/recipes/java/testing/junit5/junit5bestpractices)
- [AssertJ best practices](https://docs.openrewrite.org/recipes/java/testing/assertj/assertj)
- [SLF4J best practices](https://docs.openrewrite.org/recipes/java/logging/slf4j/slf4jbestpractices)
- [Java security best practices](https://docs.openrewrite.org/recipes/java/security/javasecuritybestpractices)
- [Find and fix vulnerable dependencies](https://docs.openrewrite.org/recipes/java/dependencies/dependencyvulnerabilitycheck)

You might even want to run some of these recipes periodically, to keep your projects up-to-date continuously.

## Helpful resources

Here's a number of links that might be helpful in case you encounter edge cases not yet covered:

- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide
- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes
- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes
- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes
- https://docs.spring.io/spring-security/reference/migration/index.html
- https://github.com/spring-projects/spring-data-commons/wiki/
- https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2022.0-Release-Notes

**Comment by doychin** [comment]
Thanks for the instructions @timtebeek . I plan to do this migration in the comming weeks.

**Pull request closed without merging**
