### PR TITLE
Admin upload speaker image

### PR DESCRIPTION
**Pull request by IvayloZashev**

### CODE REVIEW

**Comment by ivannov** [comment]
Two things from me:
- Would you please avoid reformatting pom.xml? Now it is not obvious which was the change that you added
- Could you please move your functionality in the controller in a method of its own and call that in the add method

**Comment by ivannov** [comment]
On a second thought: we need image cropping on several occasions: AbstractCfpController::saveSubmission, SpeakerController::add, SponsorController::add. So maybe it would be a good idea to extract the cropping functionality in a service of its own. It is a public class with default constructor annotated with @Service.

Then this file should be @Autowired in all the above mentioned controllers. And the public method for cropping the image should be called as parameter to setPicture, setPicture and setLogo respectively.

**Comment by IvayloZashev** [comment]
I'm  agree.
Before going further I must inform you that, especially, Speaker and Sponsor images accepts different ratio parameters for Thumbnailator evaluation !!!

Under no objections your logic but In that aspect would it be relevent for achievement.

**Comment by ivannov** [comment]
Then you may pass the ratio as parameters to the method?

**Pull request closed without merging**
